@baseUrl = http://localhost:9090
@urlPath = e166oahk87

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/66d9eb37fc6718878e8e0dda
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "66df096c118399453f91b57d",
  "receiverId": "66d9eb37fc6718878e8e0dda",
  "receiverUsername": "User3",
  "receiverAvatarColor": "grey",
  "receiverProfilePicture": "https://res.cloudinary.com/dyjgikbog/image/upload/v1725556928/66d9e8befc6718878e8e0dd0",
  "body": "3 fafda jalebi yo!! User3??",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "",
  "userTwo": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "",
  "userTwo": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "66d9e72579b67cdf7b276da4",
  "receiverId": "66d9eb37fc6718878e8e0dda"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "66df096c118399453f91b57d",
  "messageId": "66e09ec313078daf1b401127",
  "reaction": "happy",
  "type": "add"
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/66df096c118399453f91b57c/66d9e72579b67cdf7b276da4/66d9eb37fc6718878e8e0dda/deleteForEveryone
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true
