@baseUrl = http://localhost:9090
@urlPath = e166oahk87

###
GET {{baseUrl}}/{{urlPath}}/post/comments/66d774d0c288d48c6f5a9517
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/66d774d0c288d48c6f5a9517
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/66d774d0c288d48c6f5a9517/66d77cd1142f03e9b0663fe2
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "66dc3f63d1d6b3851f4a3abd",
  "postId": "66dc3f96d1d6b3851f4a3ac2",
  "comment": "This is a 1st comment",
  "profilePicture": "https://res.cloudinary.com/dyjgikbog/image/upload/v1724149982/66c470dd89c67d47b5a9e3b7"
}
