@baseUrl = http://localhost:9090
@urlPath = e166oahk87

###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/66d9e72579b67cdf7b276da4
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/66d9e72579b67cdf7b276da4
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/66d9e72579b67cdf7b276da4/66d9eb37fc6718878e8e0ddb
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/block/66d9e8befc6718878e8e0dd0
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/66d9eb37fc6718878e8e0ddb
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
