@baseUrl = http://localhost:9090
@urlPath = e166oahk87

###
GET {{baseUrl}}/{{urlPath}}/post/all/1
# GET {{baseUrl}}/{{urlPath}}/post/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/images/1
# GET {{baseUrl}}/{{urlPath}}/post/images/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

# Privacy - Public | Private | Followers
# Feelings - like | love | wow | happy | sad | angry

{
  "post": "1 post",
  "bgColor": "#123456",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dyjgikbog/image/upload/v1724149982/66c470dd89c67d47b5a9e3b7",
  "feelings": ""
}

###
POST {{baseUrl}}/{{urlPath}}/post/image/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "profilePicture": "",
  "feelings": "",
  "image": "<base64-encoded-string>"
}

###
PUT {{baseUrl}}/{{urlPath}}/post/66cc29ac63453d611cd4a24d
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "updated post yo!!",
  "bgColor": "black",
  "privacy": "Private",
  "gifUrl": "",
  "profilePicture": "<cloudinary-user-profile-picture-url>",
  "feelings": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/post/image/66cc29ac63453d611cd4a24d
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "post with image",
  "bgColor": "green",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dyjgikbog/image/upload/v1724149982/66c470dd89c67d47b5a9e3b7",
  "feelings": "sad",
  "imgId": "kzieivtcg0crdxa62ul9",
  "imgVersion": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/66c4737c89c67d47b5a9e3c7
Content-Type: application/json
Accept: application/json
withCredentials: true
